/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection */

#ifndef _Included_org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection
#define _Included_org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection
 * Method:    readRemote
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_hbase_ipc_RdmaNative_00024RdmaConnection_readRemote
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection
 * Method:    writeLocal
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hbase_ipc_RdmaNative_00024RdmaConnection_writeLocal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection
 * Method:    isRemoteReadable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_hadoop_hbase_ipc_RdmaNative_00024RdmaConnection_isRemoteReadable
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_ipc_RdmaNative_RdmaConnection
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hbase_ipc_RdmaNative_00024RdmaConnection_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
